/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ApartmentSlugRouteImport } from './routes/apartment-slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartmentsSlugRouteImport } from './routes/Apartments.$slug'

const ApartmentSlugRoute = ApartmentSlugRouteImport.update({
  id: '/apartment-slug',
  path: '/apartment-slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartmentsSlugRoute = ApartmentsSlugRouteImport.update({
  id: '/Apartments/$slug',
  path: '/Apartments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apartment-slug': typeof ApartmentSlugRoute
  '/Apartments/$slug': typeof ApartmentsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apartment-slug': typeof ApartmentSlugRoute
  '/Apartments/$slug': typeof ApartmentsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apartment-slug': typeof ApartmentSlugRoute
  '/Apartments/$slug': typeof ApartmentsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apartment-slug' | '/Apartments/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apartment-slug' | '/Apartments/$slug'
  id: '__root__' | '/' | '/apartment-slug' | '/Apartments/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApartmentSlugRoute: typeof ApartmentSlugRoute
  ApartmentsSlugRoute: typeof ApartmentsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apartment-slug': {
      id: '/apartment-slug'
      path: '/apartment-slug'
      fullPath: '/apartment-slug'
      preLoaderRoute: typeof ApartmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Apartments/$slug': {
      id: '/Apartments/$slug'
      path: '/Apartments/$slug'
      fullPath: '/Apartments/$slug'
      preLoaderRoute: typeof ApartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApartmentSlugRoute: ApartmentSlugRoute,
  ApartmentsSlugRoute: ApartmentsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
